import { useTranslation } from "react-i18next";

/**
 * A still of one of the products, framed in a browser window.
 *
 * Both screens are captured at the same 1280×980 — the shape the
 * preview window takes in the pinned column — so the framing maths is
 * identical for either and swapping one for the other costs no layout
 * change. The same is true of the recorded walkthrough parked in
 * scripts/portal-tour/, which was captured at that size for the same
 * reason.
 *
 * They come from different places, though, and only one can be
 * regenerated by a script — and one has nothing to show yet:
 *
 * - benefits: the live portal at servicos.baita.testbeds.rnp.br
 *   — re-capture with scripts/capture-portal-screen.mjs, which is
 *   worth doing whenever it changes, being a testbed.
 * - management: Figma node 1081:47103, exported at 2x and cropped to
 *   the top 1280×980. There is no running system to point a script at,
 *   so re-exporting it is a manual step.
 * - idp: nothing built to capture. The window is still drawn, with a
 *   note inside it, so the three cards keep the same shape.
 */

type Screen = "benefits" | "management" | "idp";

/** null where there is nothing to show yet — the window still gets
 *  drawn, with a note in place of a capture. */
const SOURCES: Record<Screen, string | null> = {
  benefits: "/media/screen-benefits-pt.jpg",
  management: "/media/screen-management-pt.jpg",
  idp: null,
};

export function ProductScreen({
  screen,
  variant,
}: {
  screen: Screen;
  variant: "column" | "inline";
}) {
  const { t } = useTranslation();
  const source = SOURCES[screen];

  return (
    <div className="t-screen-slot" data-variant={variant}>
      <figure className="t-screen-frame m-0">
        {/* The window chrome is markup, not part of the capture: the
            screenshot is only the viewport, and drawing the frame here
            keeps it crisp and lets it follow the page's own radii. */}
        <div className="t-screen-bar" aria-hidden="true">
          <span />
          <span />
          <span />
        </div>

        <div className="t-screen-stage">
          {source ? (
            <img
              className="t-screen-shot"
              src={source}
              alt={t(`screens.${screen}.alt`)}
              width={1280}
              height={980}
              loading="lazy"
              decoding="async"
            />
          ) : (
            // Sized in cqw against the frame, which is a container:
            // the window is ~685px wide in the pinned column and ~294px
            // inside a card on a phone, and one fixed size reads as a
            // heading at one and a whisper at the other.
            <p className="flex h-full w-full items-center justify-center bg-neutral-900 font-domine text-[clamp(20px,4.2cqw,34px)] text-neutral-400">
              {t("screens.pending")}
            </p>
          )}
        </div>
      </figure>
    </div>
  );
}
